version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/db-deployment/mysql/Dockerfile
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: ./docker/cart-craft-backend/Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: ./docker/cart-craft-frontend/Dockerfile
    ports:
      - "3000:3000"
