version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/db-deployment/mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - e-combomb-network
    volumes:
      - mysqldata:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./docker/e-combomb-backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - e-combomb-network
    environment:
      - DB_HOST=mysql
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./docker/e-combomb-frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - e-combomb-network
networks:
  e-combomb-network:
    driver: bridge
volumes:
  mysqldata:
